peca1 = input().split()
peca2 = input().split()
cod1 = int(peca1[0])
vlr1 = int(peca1[1])
qtd1 = float(peca1[2])
cod2 = int(peca2[0])
vlr2 = int(peca2[1])
qtd2 = float(peca2[2])
calc = (vlr1 * qtd1) + (vlr2 * qtd2)
print('VALOR A PAGAR: R$ {:.2f}'.format(calc))